# Generated by Django 5.0 on 2023-12-21 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0002_customuser_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='year',
            field=models.CharField(default='2025', max_length=4),
        ),
    ]
