# Generated by Django 5.0 on 2023-12-30 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0003_customuser_is_registered'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='USN',
            field=models.CharField(max_length=10),
        ),
    ]
